rm(list = ls())
devtools::install_github("whkygl/easynem", force = TRUE)
library(devtools)
create_package(getwd())
use_r("nem_database")
load_all()
exists("nem_database", where = globalenv(), inherits = FALSE)
check()
use_mit_license()
document()
use_package("shiny")
use_package("shinydashboard")
use_package("DT")
use_package("utils")
use_data_raw()
basis1 <- read.csv("data-raw/easynem_test/shiny/basis.csv")
family1 <- read.csv("data-raw/easynem_test/shiny/family.csv")
Feeding1 <- read.csv("data-raw/easynem_test/shiny/Feeding.csv")
function1 <- read.csv("data-raw/easynem_test/shiny/function.csv")
genus1 <- read.csv("data-raw/easynem_test/shiny/genus.csv")
species1 <- read.csv("data-raw/easynem_test/shiny/species.csv")
structure1 <- read.csv("data-raw/easynem_test/shiny/structure.csv")
use_data(basis1, family1, Feeding1, function1, genus1, species1, structure1, internal = TRUE)
use_r("read_nem")
use_package("readr")
use_r("easynem_example")
use_package("methods")
use_r("filter_num")
use_r("filter_name")
use_package("dplyr")
use_r("nem_trans")
use_package("tibble")
use_package("vegan")
use_r("trans_norm")
use_r("trans_rare")
use_r("trans_formula")
use_r("trans_name")
use_package("rlang")
use_r("nem_calc")
use_r("calc_beta")
use_package("remotes")
use_package("pairwiseAdonis")
use_package("agricolae")
use_package("stats")
use_package("utils")
use_r("nem_plot")
use_package("ggplot2")
use_package("ggalt")
use_r("calc_lsd")
use_r("trans_formula_v")
use_r("calc_beta2")
use_package("ggpubr")
use_r("TTest")
use_r("KruskalTest")
library(ggplot2)
bac <- read_nem(tab = easynem_example("bacotu.csv"), tax = easynem_example("bactax.csv"), meta = easynem_example("meta.csv"))
pcoa = calc_beta2(bac, pcoa, con_crop, season, method = bray)
hehe=nem_plot(pcoa, level = 0.9, type =1) + ylab("hehe") + scale_colour_discrete(limits = c("Y2","Y5","Y8","Y11"))
hehe
nmds = calc_beta2(bac, nmds, con_crop, season,method = bray)
hehe=nem_plot(nmds, type = 2)
hehe
hehe = bac |> filter_name(meta, con_crop %in% c("Y2","Y11")) |> calc_compare(.group = con_crop, y = pH, method = TTest)
hehe
hehe = bac |> filter_name(meta, con_crop %in% c("Y2","Y11")) |> calc_compare(.group = con_crop, y = pH, method = TTest, alternative = "less") |> 
  nem_plot() + scale_x_discrete(limits = c("Y2", "Y11"))
hehe
hehe = bac |> filter_name(meta, con_crop %in% c("Y2","Y11")) |> calc_compare(.group = con_crop, y = pH, method = TTest, alternative = "less") |> 
  nem_plot(type =2) + scale_x_discrete(limits = c("Y11", "Y2"))
hehe
hehe = bac |> filter_name(meta, con_crop %in% c("Y2","Y11")) |> calc_compare(.group = con_crop, y = pH, method = WilcoxTest)|> 
  nem_plot(type =2, add = "mean_sd") + scale_x_discrete(limits = c("Y2", "Y11"))
hehe
hehe = bac |> filter_name(meta, con_crop %in% c("Y2","Y11")) |> calc_compare(.group = con_crop, y = pH, method = KruskalTest)
hehe
hehe = bac |> calc_compare(.group = con_crop, y = pH, method = KruskalTest, .method = "fdr")
hehe
use_r("globals.R")
hehe = bac |> calc_compare(.group = con_crop, y = pH, method = KruskalTest) |> 
  nem_plot(type =2, add = "mean_se")
hehe
hehe = bac |> calc_compare(.group = con_crop, y = pH, method = KruskalTest) |> 
  nem_plot() + scale_x_discrete(limits = c("Y2", "Y5", "Y8", "Y11"))
hehe
use_r("trans_combine")
load_all()
bac <- read_nem(tab = easynem_example("bacotu.csv"), tax = easynem_example("bactax.csv"), meta = easynem_example("meta.csv"))
bac <- read_nem(tab = easynem_example("bacotu.csv"))
result = trans_combine(bac, c("pH","NH4"))
result@meta$pH_NH4
use_package("tidyselect")
hehe <- filter_name(bac, target = tax, Phylum == "Actinobacteria")
hehe <- filter_name(bac, target = meta, season == "Spring")
bac1 <- trans_name(bac, Class)
use_r("LSD")
use_r("HSD")
hehe <- bac |> calc_compare(con_crop, pH, method = HSD) |> nem_plot()
hehe
hehe <- bac |> calc_compare(con_crop, pH, method = HSD) |> nem_plot(type = 2, add = "mean_se")
hehe
hehe <- bac |> calc_compare(con_crop, pH, method = HSD) |> nem_plot(type = 2, add = "mean_sd")
hehe
use_r("read_nem2")
bacotu <- read.csv("C:/Users/whkyg/Desktop/BaiduSyncdisk/easynem/data-raw/read_nem2/bacotu.csv")
bactax <- read.csv("C:/Users/whkyg/Desktop/BaiduSyncdisk/easynem/data-raw/read_nem2/bactax.csv")
design <- read.csv("C:/Users/whkyg/Desktop/BaiduSyncdisk/easynem/data-raw/read_nem2/design.csv")
bac <- read_nem2(tab = bacotu, tax = bactax, meta = design)
bac
bac <- read_nem2(tab = bacotu, tax = bactax)
bac
