rm(list = ls())
devtools::install_github("whkygl/easynem")
library(devtools)
create_package(getwd())
use_r("nem_database")
load_all()
exists("nem_database", where = globalenv(), inherits = FALSE)
check()
use_mit_license()
document()
use_package("shiny")
use_package("shinydashboard")
use_package("DT")
use_package("utils")
use_data_raw()
basis1 <- read.csv("data-raw/easynem_test/shiny/basis.csv")
family1 <- read.csv("data-raw/easynem_test/shiny/family.csv")
Feeding1 <- read.csv("data-raw/easynem_test/shiny/Feeding.csv")
function1 <- read.csv("data-raw/easynem_test/shiny/function.csv")
genus1 <- read.csv("data-raw/easynem_test/shiny/genus.csv")
species1 <- read.csv("data-raw/easynem_test/shiny/species.csv")
structure1 <- read.csv("data-raw/easynem_test/shiny/structure.csv")
use_data(basis1, family1, Feeding1, function1, genus1, species1, structure1, internal = TRUE)
use_r("read_nem")
use_package("readr")
use_r("easynem_example")
use_package("methods")
use_r("filter_num")
use_r("filter_name")
use_package("dplyr")
use_r("nem_trans")
use_package("tibble")
use_package("vegan")
use_r("trans_norm")
use_r("trans_rare")
use_r("trans_formula")
use_r("trans_name")
use_package("rlang")
use_r("nem_calc")
use_r("calc_beta")
use_package("remotes")
use_package("pairwiseAdonis")
use_package("stats")
use_package("utils")
