devtools::install_github("whkygl/easynem")
library(easynem)
?read_nem2
easynem <- read_nem2(tab = nemtab, tax = nemtax, meta = nemmeta)
easynem <- read_nem2(tab = nemtab)
head(easynem@tab)
easynem <- read_nem2(tax = nemtax)
head(easynem@tax)
easynem <- read_nem2(meta = nemmeta)
head(easynem@meta)
easynem <- read_nem2(tab = nemtab, tax = nemtax)
head(easynem@tab)
head(easynem@tax)
easynem <- read_nem2(tab = nemtab, meta = nemmeta)
head(easynem@tab)
head(easynem@meta)
easynem <- read_nem2(tax = nemtax, meta = nemmeta)
head(easynem@tax)
head(easynem@meta)

